server:
  # Railway te da un puerto dinámico en la var de entorno PORT
  port: ${PORT}
  address: 0.0.0.0

spring:
  datasource:
    # Deja estas refs a variables: ya las tienes en Railway
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        # Evita errores por nombres como `user`, `role`, etc.
        globally_quoted_identifiers: true
    # Puedes ponerlo en false cuando todo quede estable
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    # CLAVE para tu error: permite ejecutar V2 aunque la BD ya esté en 7
    out-of-order: true
    # Déjalo en false a menos que vengas de una BD ya creada a mano
    baseline-on-migrate: ${SPRING_FLYWAY_BASELINE_ON_MIGRATE:false}

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
nano src/main/resources/application-prod.yml   # pega el contenido de arriba
# guarda (Ctrl+O, Enter) y sal (Ctrl+X)

git add src/main/resources/application-prod.yml
git commit -m "prod: puerto dinámico + Flyway out-of-order + quoted identifiers"
git push origin main
server:
  # Railway te da un puerto dinámico en la var de entorno PORT
  port: ${PORT}
  address: 0.0.0.0

spring:
  datasource:
    # Deja estas refs a variables: ya las tienes en Railway
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        # Evita errores por nombres como `user`, `role`, etc.
        globally_quoted_identifiers: true
    # Puedes ponerlo en false cuando todo quede estable
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    # CLAVE para tu error: permite ejecutar V2 aunque la BD ya esté en 7
    out-of-order: true
    # Déjalo en false a menos que vengas de una BD ya creada a mano
    baseline-on-migrate: ${SPRING_FLYWAY_BASELINE_ON_MIGRATE:false}

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
