server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/grhdatabase?useUnicode=true&characterEncoding=utf-8&connectionCollation=utf8mb4_unicode_ci

    username: root
    password: D0s+Un0=3
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    locations: classpath:mb/migration
    url: jdbc:mysql://localhost:3306/grhdatabase
    user: root
    password: D0s+Un0=3
    enabled: true
    baseline-on-migrate: true
    driver-class-name: com.mysql.cj.jdbc.Driver

