server:
  port: ${PORT:8080}   # usa PORT de Railway, con 8080 por defecto
  address: 0.0.0.0

spring:
  datasource:
    # puedes definir SPRING_DATASOURCE_URL en Railway o dejar que use las vars MYSQLHOST, etc.
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://${MYSQLHOST}:${MYSQLPORT:3306}/${MYSQLDATABASE}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8}
    username: ${SPRING_DATASOURCE_USERNAME:${MYSQLUSER}}
    password: ${SPRING_DATASOURCE_PASSWORD:${MYSQLPASSWORD}}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate         # valida el esquema contra las entidades
    open-in-view: false
    show-sql: false              # en prod mejor oculto
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true    # si ya existen tablas
    validate-on-migrate: true
    out-of-order: false
    clean-disabled: true

logging:
  level:
    org.flywaydb: DEBUG
