server:
  address: 0.0.0.0
  port: ${PORT:8080}

spring:
  datasource:
    # Usa SPRING_DATASOURCE_URL si existe; si no, toma las MYSQL* de Railway
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://${MYSQLHOST}:${MYSQLPORT:3306}/${MYSQLDATABASE}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8}
    username: ${SPRING_DATASOURCE_USERNAME:${MYSQLUSER}}
    password: ${SPRING_DATASOURCE_PASSWORD:${MYSQLPASSWORD}}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    out-of-order: false
    clean-disabled: true

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

logging:
  level:
    root: INFO
    org.flywaydb: INFO
