server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/grhdatabase?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&connectionCollation=utf8mb4_unicode_ci
    username: root
    password: "D0s+Un0=3"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    # Usa baseline-on-migrate SOLO si ya existen tablas previas en esa BD:
    baseline-on-migrate: true
